# Generated by Django 5.2.6 on 2025-09-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('gto_playload', models.IntegerField(verbose_name='Полезная нагрузка (кг)')),
            ],
            options={
                'verbose_name': 'Ракета-носитель',
                'verbose_name_plural': 'Ракеты-носители',
            },
        ),
    ]
