# Generated by Django 5.2.6 on 2025-09-11 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpacePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название космодрома')),
                ('descriptionSP', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('location', models.IntegerField(verbose_name='Широта космодрома')),
            ],
            options={
                'verbose_name': 'Космодром',
                'verbose_name_plural': 'Космодромы',
            },
        ),
        migrations.CreateModel(
            name='CalculationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('result', models.IntegerField(verbose_name='Результат вычислений')),
                ('rocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rocket.launchvehicle', verbose_name='Ракета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rocket.spaceport', verbose_name='Порт')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
