# Generated by Django 5.2.6 on 2025-09-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocket', '0002_spaceport_calculationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchvehicle',
            name='imagerocket',
            field=models.ImageField(blank=True, null=True, upload_to='rockets/', verbose_name='Изображение'),
        ),
    ]
