# Generated by Django 5.2.6 on 2025-09-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocket', '0003_launchvehicle_imagerocket'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchvehicle',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
