# Generated by Django 5.2.6 on 2025-10-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocket', '0004_launchvehicle_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationrequest',
            name='port',
        ),
        migrations.AddField(
            model_name='calculationrequest',
            name='location',
            field=models.IntegerField(blank=True, null=True, verbose_name='Широта космодрома'),
        ),
        migrations.AddField(
            model_name='calculationrequest',
            name='port_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Порт'),
        ),
        migrations.DeleteModel(
            name='SpacePort',
        ),
    ]
