# Generated by Django 5.2.6 on 2025-09-22 10:11

import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocket', '0004_launchvehicle_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchvehicle',
            name='imagerocket',
            field=models.ImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='django-media'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='Изображение'),
        ),
    ]
