# Generated by Django 5.2.6 on 2025-10-13 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocket', '0005_remove_calculationrequest_port_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='launchvehicle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='calculationrequest',
            name='rocket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rocket.launchvehicle', verbose_name='Ракета'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Черновик', 'Draft'), ('Удален', 'Deleted'), ('В расчете', 'Formed'), ('Расчет завершен', 'Completed'), ('Ошибка в расчете', 'Rejected')], default='Черновик', max_length=25)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('formation_datetime', models.DateTimeField(blank=True, null=True)),
                ('completion_datetime', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='calculationrequest',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rocket.order', verbose_name='Пользователь'),
        ),
    ]
